### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by tablatronix** [tablatronix/3dmodels#2]
- [ ] standardize all screw spacing, and hole size, M3-5 capable?
- [ ] standardsize all thicknesses
- [ ] Allow all to be mounted via angle wedge, to tilt forward.
